# Guition.ESP32-P4-jc4880p443
#
# Hardware configuration file

substitutions:
  # Screen Size (Configured as Lanscape)
  screen_height: 480
  screen_width: 800

esphome:
  min_version: 2026.1.0
  project:
    name: "Guition.ESP32-P4-jc4880p443"
    version: "1.0"

esp32:
  variant: esp32p4
  flash_size: 16MB
  cpu_frequency: 360MHz
  framework:
    type: esp-idf
    advanced:
      enable_idf_experimental_features: true

esp_ldo:
  - channel: 3
    voltage: 2.5V

psram:
  mode: hex
  speed: 200MHz

preferences:
  flash_write_interval: 5min

#-------------------------------------------
# Network hardware
#-------------------------------------------  
esp32_hosted:
  variant: ESP32C6
  reset_pin: GPIO54
  cmd_pin: GPIO19
  clk_pin: GPIO18
  d0_pin: GPIO14
  d1_pin: GPIO15
  d2_pin: GPIO16
  d3_pin: GPIO17
  active_high: true  

# -------------------------------------------
# Internal outputs
# -------------------------------------------
output:
  # Backlight LED
  - platform: ledc
    pin: GPIO23  
    id: gpio_backlight_pwm

light:
  - platform: monochromatic
    output: gpio_backlight_pwm
    name: Display Backlight
    icon: mdi:lightbulb-on
    id: display_backlight
    restore_mode: ALWAYS_ON

# -------------------------------------------
# i2c bus
# -------------------------------------------    
i2c:
  - id: bus_a
    sda: GPIO7  
    scl: GPIO8  
    scan: true
    frequency: 400kHz

# -------------------------------------------
# Touchscreen
# -------------------------------------------
touchscreen:
  - platform: gt911
    i2c_id: bus_a
    id: my_touchscreen
    reset_pin: GPIO3
    transform: #This is for 90 degree display rotation
      swap_xy: true
      mirror_x: false
      mirror_y: true
    # on_touch:
      # - logger.log:
            # format: Touch at (%d, %d)
            # args: [touch.x, touch.y]
      # - lambda: |-
            # ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
                # touch.x,
                # touch.y,
                # touch.x_raw,
                # touch.y_raw
                # );

# -------------------------------------------
# Display
# -------------------------------------------
display:
  - platform: mipi_dsi
    id: device_display
    model: JC4880P443
    byte_order: little_endian
    rotation: 90

# Special LVGL settings required for this display  
lvgl:
  byte_order: little_endian

# -------------------------------------------
# Audio - speaker/mic
# ------------------------------------------- 
audio_dac:
  - platform: es8311
    id: esp7311_dac
    address: 0x18
    i2c_id: bus_a

i2s_audio:
  - id: i2s_bus
    i2s_lrclk_pin: GPIO10 # WS / LRCK
    i2s_bclk_pin: GPIO12  # BCLK
    i2s_mclk_pin: GPIO13  # ES8311 usually requires a Master Clock

microphone:
  - platform: i2s_audio
    id: es8311_mic
    i2s_audio_id: i2s_bus
    i2s_din_pin: GPIO48  # Data In from the Codec
    adc_type: external
    pdm: false           # ES8311 uses standard I2S, not PDM
    channel: left

speaker:
  - platform: i2s_audio
    id: es8311_hardware_out
    i2s_audio_id: i2s_bus
    i2s_dout_pin: GPIO9
    dac_type: external
    audio_dac: esp7311_dac
  - platform: mixer
    id: audio_mixer
    output_speaker: es8311_hardware_out
    source_speakers:
      - id: spk_announcement
      - id: spk_media

media_player:
  - platform: speaker
    name: "XL Speaker"
    id: xl_media_player
    # This section is now mandatory for the 'speaker' platform
    announcement_pipeline:
      speaker: spk_announcement
    media_pipeline:
      speaker: spk_media